name: backend
version: 0.1.0.0
github: "githubuser/backend"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2018 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

  # Metadata used when publishing your package
  # synopsis:            Short description of your package
  # category:            Web
  # To avoid duplicated efforts in documentation and dealing with the
  # complications of embedding Haddock markup inside cabal files, it is
  # common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/backend#readme>

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Werror

library:
  source-dirs: src
  dependencies:
    - selda
    - selda-postgresql
    - servant
    - servant-server
    - servant-auth-server
    - cookie
    - text
    - wai
    - aeson
    - warp
    - bytestring
    - transformers # throwError comes from here
    - mtl
    - opaleye
    - time
    - product-profunctors
    - postgresql-simple
    - servant-docs
    - cryptonite
    - memory
    - uuid
    - exceptions

executables:
  backend-exe:
    rebuild-ghc-options: true
    main: Main.hs
    source-dirs: app

    dependencies:
      - backend

tests:
  backend-test:
    main: Spec.hs
    source-dirs: test

    dependencies:
      - backend